"""migrate

Revision ID: 104c8cba81e9
Revises: b07f5f00eea9
Create Date: 2022-11-09 09:32:32.863474

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '104c8cba81e9'
down_revision = 'b07f5f00eea9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
