"""migrate

Revision ID: 2d1e59ab55a4
Revises: 104c8cba81e9
Create Date: 2022-11-09 09:35:44.758605

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2d1e59ab55a4'
down_revision = '104c8cba81e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_created_by_fkey', 'news', type_='foreignkey')
    op.drop_constraint('news_updated_by_fkey', 'news', type_='foreignkey')
    op.drop_column('news', 'updated_by')
    op.drop_column('news', 'created_by')
    op.alter_column('users', 'discord_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('news', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('news_updated_by_fkey', 'news', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('news_created_by_fkey', 'news', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
