"""migrate

Revision ID: 33ce5100f7d3
Revises: 453649d6da90
Create Date: 2022-11-09 09:16:46.739916

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '33ce5100f7d3'
down_revision = '453649d6da90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
