"""migrate

Revision ID: 453649d6da90
Revises: 94f4d6f6855e
Create Date: 2022-11-09 09:01:44.399871

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '453649d6da90'
down_revision = '94f4d6f6855e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
