"""migrate

Revision ID: 4681ed105438
Revises: 
Create Date: 2022-11-24 10:17:59.661426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4681ed105438'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False))
    op.drop_column('comments', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comments', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
