"""fix big integer

Revision ID: 94f4d6f6855e
Revises: f73e78d26d24
Create Date: 2022-11-09 07:12:05.467121

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '94f4d6f6855e'
down_revision = 'f73e78d26d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
