"""test migration

Revision ID: f73e78d26d24
Revises: 
Create Date: 2022-11-09 04:20:23.737463

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f73e78d26d24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('news_tag_fkey', 'news', type_='foreignkey')
    op.drop_column('news', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('news_tag_fkey', 'news', 'tags', ['tag'], ['id'])
    # ### end Alembic commands ###
